# Generated by Django 5.0.1 on 2024-01-25 13:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_tableofcontent_tag_alter_subscriber_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.webp', max_length=255, null=True, verbose_name='image'),
        ),
    ]
